name: approval
description: "Epoool Approval"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  path: ^1.9.0
  url_launcher: ^6.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  equatable: ^2.0.5
  go_router: ^17.0.0
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  share_plus: ^11.1.0
  chucker_flutter: ^1.7.2
  file_picker: ^10.3.3
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3

  # riverpod state management
  flutter_riverpod: ^3.0.0
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # device information
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0

  # connection management
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0

  # permission
  permission_handler: ^12.0.1

  # firebase
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_crashlytics: ^5.0.1

  # location
  geolocator: ^14.0.1
  location: ^8.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  # dart run build_runner watch -d
  build_runner: ^2.7.1
  json_serializable: ^6.10.0
  riverpod_generator: ^3.0.0
  # flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  analyzer_plugin: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
